/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oserooooo;

public class App {

    public static void main(String[] args) {

        Game game = new Game();                
        for (int i = 0; i < 1; i++) {
            game.start();
        }     

        // 負けリストをresourcesに出力する
        game.outputLoseInfoList();
    }
}
